name: Dev Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.x'
        cache: true

    - name: Setup Just
      uses: taiki-e/install-action@just

    - name: Run CI Target
      run: |
        just ci
